# -*- coding: utf-8 -*-
"""automate_David_Sebastian_Sutandy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LJHWtbMrfltczx7WXyWtz1J_HqZpJbbG

#  Data Preprocessing Otomatis
"""

import pandas as pd
import argparse
import os
import sys


def preprocess_data(input_path, output_path):

    print(f"Membaca dataset dari: {input_path}")

    try:
        df = pd.read_csv(input_path)
    except Exception as e:
        print(f"Gagal membaca file: {e}")
        sys.exit(1)

    # Drop duplicate rows
    df = df.drop_duplicates()

    # Cleaning & encoding target
    df['gender'] = df['gender'].astype(str).str.lower().str.strip()
    df['gender'] = df['gender'].map({'male': 0, 'female': 1})

    # Drop invalid target
    df = df.dropna(subset=['gender'])

    print(f"Preprocessing selesai. Total data: {df.shape[0]}")

    # Ensure output directory exists
    output_dir = os.path.dirname(output_path)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)

    df.to_csv(output_path, index=False)
    print(f"Dataset hasil preprocessing disimpan di: {output_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog="Automated Preprocessing",
        description="Script otomatis untuk preprocessing dataset gender classification"
    )

    io_args = parser.add_argument_group("Input / Output Configuration")

    io_args.add_argument(
        "--input-path",
        type=str,
        required=True,
        help="Lokasi file dataset mentah (CSV)"
    )

    io_args.add_argument(
        "--output-path",
        type=str,
        default="preprocessed/gender_clean.csv",
        help="Lokasi penyimpanan dataset hasil preprocessing"
    )

    args = parser.parse_args()

    preprocess_data(
        input_path=args.input_path,
        output_path=args.output_path
    )